name: carest_app
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  fonts:
    - family: Zen-M
      fonts:
          - asset: assets/font/ZenMaruGothic-Medium.ttf

    - family: Zen-B
      fonts:
          - asset: assets/font/ZenMaruGothic-Bold.ttf  

    - family: Zen-R
      fonts:
          - asset: assets/font/ZenMaruGothic-Regular.ttf  

    - family: Zen-Bl
      fonts:
          - asset: assets/font/ZenMaruGothic-Black.ttf  
      
    - family: Zen-L
      fonts:
          - asset: assets/font/ZenMaruGothic-Light.ttf  



  assets:
    - assets/images/
    - assets/images/pushed_button.png

  uses-material-design: true